### ISSUE TITLE
Incase this helps (Shapekeys)

### ISSUE THREAD

**Issue by Apoc1011** [SpectrumQT/WWMI#1] opened 2024-07-02 20:00 UTC
Hello Spectrum,  I know you are working on the issues regarding shapekeys. I doubt this info is news to you or even relevant, but in the case that it helps, here are the observations I've noticed.

Character Tested :
- Yinlin

Blender Notes:  
- Tested with a standard dump procedure using your tools.
- Used edited shapekeys for the arms ( deleted and removed some to see there differnce )
- Also used a shapekey wrap addon ( to restore default shape keys from a freshly imported object to an edited mesh )

Observation:
- From what i've noticed, exported shape keys seem to work fine. When modifying them
![yinny mang](https://github.com/SpectrumQT/WWMI/assets/174495042/aeca067f-ddf7-4246-b152-a54a0e03f674)
![yinny](https://github.com/SpectrumQT/WWMI/assets/174495042/7e48459f-caa4-407a-ad47-c673b1da001a)

- Any modifications, appear as normal, with the effects of the weights applied.

https://github.com/SpectrumQT/WWMI/assets/174495042/1da90443-624c-4304-a38b-c4d2c25d14ee

- However, when exporting the same mod with no changes to the shape key, you still get some deformation.
![yin penny](https://github.com/SpectrumQT/WWMI/assets/174495042/5de2c249-e502-48b0-a2d9-495064a5baf1)

https://github.com/SpectrumQT/WWMI/assets/174495042/25119873-679b-4787-9a43-b7102d274443

- Even when testing all shape keys removed, the results are the same as shown in the video above.
- If I am allowed to take a guess, at risk of being wrong, or stating the obvious. It feels like the shape keys are being slightly modified after export.
- At first I thought, the import of object, from the frame dump, was missing some shape keys somehow,  
- But after taking a closer looking at it, I feel like there are some discrepancies in the way the shapekeys are being read, after the mod is exported.

https://github.com/SpectrumQT/WWMI/assets/174495042/af083abc-31f6-4eee-afa6-121867e0cf52

This is beyond my expertise, so I hope this information is helpful.

**Comment by SpectrumQT** [comment] 2024-07-02 21:00
Hello! Yes, I've preliminary identified the scope of the isssue to be Shape Key CS chain related, and your findings aren't contradicting with it. I'm almost sure that it's caused by some changes in said shaders' data IO structure, and now it's not fully compatible with my custom shaders.

It just requires intense HLSL debug session to detect the exact cause, and today I've prioritised other issues.  Hopefully, tomorrow I'll have enough time to do proper debugging.

**Comment by Apoc1011** [comment] 2024-07-03 04:12
Sounds great. I wish you best of luck

**Comment by SpectrumQT** [comment] 2024-07-03 17:21
Shape keys handling is fixed in [WWMI 0.6.1](https://github.com/SpectrumQT/WWMI/releases/tag/v0.6.1) and [WWMI Tools 0.8.3](https://github.com/SpectrumQT/WWMI-TOOLS/releases/tag/v0.8.3) updates. Make sure to re-export your mods. :)

**Closed by SpectrumQT** 2024-07-03 17:21 UTC
